"""Exact scans of balancing-transfer increments beyond Lee balls.

The script studies finite, unconditional, permutation-invariant lattice sets
``A,B`` through their cross-covariogram

    g_{A,B}(u) = |{x in A : x + u in B}|.

For every directed Robin Hood edge ``lambda -> mu`` on a fixed nonnegative
L1 shell, it records the exact integer increment

    g_{A,B}(mu) - g_{A,B}(lambda).

No floating-point geometry is used for the counts.  The optional two-
dimensional lattice-convexity classifier uses an exact integer convex-hull and
orientation test.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from itertools import combinations, product
import json
from pathlib import Path
from typing import Callable, Iterable, Iterator, Sequence


Point = tuple[int, ...]
Partition = tuple[int, ...]


@dataclass(frozen=True)
class LatticeBody:
    family: str
    parameter: str
    dimension: int
    points: frozenset[Point]

    @property
    def radius_l1(self) -> int:
        return max((sum(abs(v) for v in x) for x in self.points), default=0)

    @property
    def radius_linf(self) -> int:
        return max((max(abs(v) for v in x) for x in self.points), default=0)


@dataclass(frozen=True)
class Witness:
    family: str
    left_parameter: str
    right_parameter: str
    dimension: int
    shell: int
    source: Partition
    target: Partition
    old_overlap: int
    new_overlap: int

    @property
    def increment(self) -> int:
        return self.new_overlap - self.old_overlap

    def as_dict(self) -> dict[str, object]:
        return {
            "family": self.family,
            "left": self.left_parameter,
            "right": self.right_parameter,
            "dimension": self.dimension,
            "shell": self.shell,
            "source": self.source,
            "target": self.target,
            "old": self.old_overlap,
            "new": self.new_overlap,
            "increment": self.increment,
        }


def integer_partitions(total: int, dimension: int) -> tuple[Partition, ...]:
    """Partitions of ``total`` into exactly ``dimension`` nonnegative parts."""

    def rec(remaining: int, slots: int, cap: int) -> Iterator[Partition]:
        if slots == 0:
            if remaining == 0:
                yield ()
            return
        for head in range(min(cap, remaining), -1, -1):
            for tail in rec(remaining - head, slots - 1, head):
                yield (head,) + tail

    return tuple(rec(total, dimension, total))


def transfer_edges(shell: int, dimension: int) -> tuple[tuple[Partition, Partition], ...]:
    """All arcs generated by one unit balancing operation and sorting.

    These arcs need not be Hasse covers of the dominance poset; the manuscript
    therefore calls them unit-transfer arcs throughout.
    """

    edges: set[tuple[Partition, Partition]] = set()
    for source in integer_partitions(shell, dimension):
        for donor in range(dimension):
            for recipient in range(dimension):
                if source[donor] < source[recipient] + 2:
                    continue
                moved = list(source)
                moved[donor] -= 1
                moved[recipient] += 1
                target = tuple(sorted(moved, reverse=True))
                if source != target:
                    edges.add((source, target))
    return tuple(sorted(edges))


def centered_parity_interval(extent: int) -> frozenset[int]:
    """Return ``{-extent,-extent+2,...,extent}`` exactly."""

    if extent < 0:
        raise ValueError("extent must be nonnegative")
    return frozenset(range(-extent, extent + 1, 2))


def atomic_exposure(alpha: int, beta: int, difference: int) -> int:
    """Exact overlap increment when a centered parity interval moves by two."""

    if min(alpha, beta) < 0 or difference < 2:
        raise ValueError("nonnegative extents and difference >= 2 are required")
    if (alpha - beta + difference) % 2:
        raise ValueError("the shifted intervals must lie in the same parity coset")
    first = centered_parity_interval(alpha)
    second = centered_parity_interval(beta)
    old = len(first & frozenset(value - difference for value in second))
    new = len(first & frozenset(value - (difference - 2) for value in second))
    return new - old


def symmetric_points(
    dimension: int,
    coordinate_bound: int,
    predicate: Callable[[tuple[int, ...]], bool],
) -> frozenset[Point]:
    """Generate a body from a predicate on absolute coordinates."""

    return frozenset(
        x
        for x in product(range(-coordinate_bound, coordinate_bound + 1), repeat=dimension)
        if predicate(tuple(abs(v) for v in x))
    )


def capped_cross_polytope(dimension: int, total_radius: int, cap: int) -> LatticeBody:
    points = symmetric_points(
        dimension,
        min(total_radius, cap),
        lambda a: sum(a) <= total_radius and max(a, default=0) <= cap,
    )
    return LatticeBody("capped-cross", f"T={total_radius},R={cap}", dimension, points)


def l1_plus_linf(dimension: int, l1_radius: int, cube_radius: int) -> LatticeBody:
    """Integer points of ``l1_radius B1 + cube_radius B_infinity``.

    Membership is exact because the L1 distance from ``x`` to the cube
    ``[-b,b]^d`` equals ``sum_i max(|x_i|-b,0)``.
    """

    bound = l1_radius + cube_radius
    points = symmetric_points(
        dimension,
        bound,
        lambda x: sum(max(v - cube_radius, 0) for v in x) <= l1_radius,
    )
    return LatticeBody("B1-plus-Binf", f"a={l1_radius},b={cube_radius}", dimension, points)


def lp_ball(dimension: int, p: int | str, radius: int) -> LatticeBody:
    if p == "inf":
        predicate = lambda x: max(x, default=0) <= radius
    else:
        exponent = int(p)
        budget = radius**exponent
        predicate = lambda x: sum(v**exponent for v in x) <= budget
    points = symmetric_points(dimension, radius, predicate)
    return LatticeBody("lp-ball", f"p={p},r={radius}", dimension, points)


def cross_covariogram(left: frozenset[Point], right: frozenset[Point], shift: Point) -> int:
    """Return ``|left intersect (right-shift)|`` exactly."""

    return sum(tuple(x[i] + shift[i] for i in range(len(shift))) in right for x in left)


def scan_pair(
    left: LatticeBody,
    right: LatticeBody,
    max_shell: int | None = None,
) -> tuple[Counter[int], list[Witness]]:
    if left.dimension != right.dimension:
        raise ValueError("body dimensions differ")
    dimension = left.dimension
    if max_shell is None:
        max_shell = left.radius_l1 + right.radius_l1
    histogram: Counter[int] = Counter()
    witnesses: list[Witness] = []
    for shell in range(2, max_shell + 1):
        for source, target in transfer_edges(shell, dimension):
            old = cross_covariogram(left.points, right.points, source)
            new = cross_covariogram(left.points, right.points, target)
            delta = new - old
            histogram[delta] += 1
            if delta <= 0:
                witnesses.append(
                    Witness(
                        left.family,
                        left.parameter,
                        right.parameter,
                        dimension,
                        shell,
                        source,
                        target,
                        old,
                        new,
                    )
                )
    return histogram, witnesses


def orbit_partitions(dimension: int, bound: int) -> tuple[Partition, ...]:
    return tuple(
        values
        for values in product(range(bound + 1), repeat=dimension)
        if all(values[i] >= values[i + 1] for i in range(dimension - 1))
    )


def partition_downset_ideals(dimension: int, bound: int) -> tuple[frozenset[Partition], ...]:
    """All ideals in the componentwise poset of sorted absolute-value orbits."""

    elements = orbit_partitions(dimension, bound)
    index = {element: i for i, element in enumerate(elements)}
    lower_masks: list[int] = []
    for element in elements:
        mask = 0
        for lower in elements:
            if all(lower[i] <= element[i] for i in range(dimension)):
                mask |= 1 << index[lower]
        lower_masks.append(mask)

    ideals: list[frozenset[Partition]] = []
    for mask in range(1 << len(elements)):
        if not (mask & 1):  # The zero orbit must occur in every nonempty downset.
            continue
        if any((mask & (1 << i)) and (lower_masks[i] & ~mask) for i in range(len(elements))):
            continue
        ideals.append(frozenset(element for i, element in enumerate(elements) if mask & (1 << i)))
    return tuple(ideals)


def body_from_orbit_ideal(
    dimension: int,
    bound: int,
    ideal: frozenset[Partition],
    index: int,
) -> LatticeBody:
    points = symmetric_points(
        dimension,
        bound,
        lambda x: tuple(sorted(x, reverse=True)) in ideal,
    )
    maximal = sorted(
        (
            x
            for x in ideal
            if not any(x != y and all(x[i] <= y[i] for i in range(dimension)) for y in ideal)
        ),
        reverse=True,
    )
    parameter = f"ideal#{index};max={maximal}"
    return LatticeBody("symmetric-downset", parameter, dimension, points)


def _cross(o: tuple[int, int], a: tuple[int, int], b: tuple[int, int]) -> int:
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def convex_hull_2d(points: Iterable[tuple[int, int]]) -> tuple[tuple[int, int], ...]:
    pts = sorted(set(points))
    if len(pts) <= 1:
        return tuple(pts)
    lower: list[tuple[int, int]] = []
    for p in pts:
        while len(lower) >= 2 and _cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper: list[tuple[int, int]] = []
    for p in reversed(pts):
        while len(upper) >= 2 and _cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    return tuple(lower[:-1] + upper[:-1])


def point_in_convex_polygon(point: tuple[int, int], hull: Sequence[tuple[int, int]]) -> bool:
    if len(hull) == 1:
        return point == hull[0]
    if len(hull) == 2:
        return _cross(hull[0], hull[1], point) == 0 and all(
            min(hull[0][i], hull[1][i]) <= point[i] <= max(hull[0][i], hull[1][i])
            for i in range(2)
        )
    signs = [_cross(hull[i], hull[(i + 1) % len(hull)], point) for i in range(len(hull))]
    return all(value >= 0 for value in signs) or all(value <= 0 for value in signs)


def is_lattice_convex_2d(body: LatticeBody) -> bool:
    hull = convex_hull_2d(body.points)
    bound = body.radius_linf
    for point in product(range(-bound, bound + 1), repeat=2):
        if point_in_convex_polygon(point, hull) != (point in body.points):
            return False
    return True


def has_centered_diagonal_fibers(body: LatticeBody) -> bool:
    """Test the exact combinatorial hypothesis used by the general proof.

    For every active coordinate pair, every residual vector and every value of
    ``r=x_i+x_j``, the available ``w=x_i-x_j`` values must form a centered
    interval in the parity lattice ``r+2Z``.  Convex unconditional
    permutation-invariant bodies have this property, but convexity itself is
    not needed by the transfer proof once the property is known.
    """

    dimension = body.dimension
    for first in range(dimension):
        for second in range(first + 1, dimension):
            fibers: dict[tuple[tuple[int, ...], int], set[int]] = defaultdict(set)
            for point in body.points:
                residual = tuple(point[i] for i in range(dimension) if i not in (first, second))
                r = point[first] + point[second]
                w = point[first] - point[second]
                fibers[(residual, r)].add(w)
            for (_, r), values in fibers.items():
                extent = max(abs(w) for w in values)
                expected = set(range(-extent, extent + 1, 2))
                if extent % 2 != r % 2:
                    return False
                if values != expected:
                    return False
    return True


def minimal_witness(witnesses: Iterable[Witness], negative_only: bool = False) -> Witness | None:
    eligible = [w for w in witnesses if w.increment < 0 or (w.increment == 0 and not negative_only)]
    if not eligible:
        return None
    return min(
        eligible,
        key=lambda w: (
            w.dimension,
            w.shell,
            w.old_overlap + w.new_overlap,
            len(w.left_parameter) + len(w.right_parameter),
            w.source,
            w.target,
        ),
    )


def summarize_family(bodies: Sequence[LatticeBody], pair_mode: str = "all") -> dict[str, object]:
    if pair_mode not in {"all", "equal", "unequal"}:
        raise ValueError("pair_mode must be all, equal, or unequal")
    pairs: list[tuple[LatticeBody, LatticeBody]] = []
    if pair_mode in {"all", "unequal"}:
        pairs.extend(combinations(bodies, 2))
    if pair_mode in {"all", "equal"}:
        pairs.extend((body, body) for body in bodies)
    increment_histogram: Counter[int] = Counter()
    negative: list[Witness] = []
    zero: list[Witness] = []
    pair_signs: Counter[str] = Counter()
    for left, right in pairs:
        histogram, witnesses = scan_pair(left, right)
        increment_histogram.update(histogram)
        has_negative = any(w.increment < 0 for w in witnesses)
        has_zero = any(w.increment == 0 and (w.old_overlap or w.new_overlap) for w in witnesses)
        pair_signs["negative" if has_negative else "nonnegative"] += 1
        if has_zero:
            pair_signs["active-zero"] += 1
        negative.extend(w for w in witnesses if w.increment < 0)
        zero.extend(w for w in witnesses if w.increment == 0 and (w.old_overlap or w.new_overlap))
    return {
        "body_count": len(bodies),
        "pair_mode": pair_mode,
        "pair_count": len(pairs),
        "edge_evaluations": sum(increment_histogram.values()),
        "pair_signs": dict(pair_signs),
        "increment_min": min(increment_histogram, default=None),
        "increment_max": max(increment_histogram, default=None),
        "negative_edge_count": sum(count for delta, count in increment_histogram.items() if delta < 0),
        "zero_edge_count": increment_histogram.get(0, 0),
        "minimal_negative": minimal_witness(negative, negative_only=True).as_dict() if negative else None,
        "minimal_active_zero": minimal_witness(zero).as_dict() if zero else None,
    }


def run_parameterized_families() -> dict[str, object]:
    summaries: dict[str, object] = {}
    for dimension in (2, 3):
        capped = [
            capped_cross_polytope(dimension, total, cap)
            for total in range(1, 7 if dimension == 2 else 5)
            for cap in range(1, total + 1)
        ]
        summaries[f"capped-cross-d{dimension}"] = summarize_family(capped)

        sums = [
            l1_plus_linf(dimension, a, b)
            for a in range(0, 5 if dimension == 2 else 4)
            for b in range(0, 4)
            if a + b > 0
        ]
        summaries[f"B1-plus-Binf-d{dimension}"] = summarize_family(sums)

        lp = [
            lp_ball(dimension, p, radius)
            for p in (1, 2, 3, 4, 6, "inf")
            for radius in range(1, 6 if dimension == 2 else 4)
        ]
        summaries[f"lp-ball-d{dimension}"] = summarize_family(lp)
    return summaries


def run_downset_families() -> dict[str, object]:
    summaries: dict[str, object] = {}
    for dimension, bound in ((2, 4), (3, 2)):
        ideals = partition_downset_ideals(dimension, bound)
        bodies = [body_from_orbit_ideal(dimension, bound, ideal, i) for i, ideal in enumerate(ideals)]
        summaries[f"all-downsets-d{dimension}-M{bound}"] = summarize_family(bodies)
        summaries[f"equal-downsets-d{dimension}-M{bound}"] = summarize_family(
            bodies, pair_mode="equal"
        )
        summaries[f"unequal-downsets-d{dimension}-M{bound}"] = summarize_family(
            bodies, pair_mode="unequal"
        )
        diagonal = [body for body in bodies if has_centered_diagonal_fibers(body)]
        summaries[f"diagonal-fiber-downsets-d{dimension}-M{bound}"] = summarize_family(diagonal)
        if dimension == 2:
            convex = [body for body in bodies if is_lattice_convex_2d(body)]
            summaries[f"lattice-convex-downsets-d2-M{bound}"] = summarize_family(convex)
    # One larger three-dimensional box is affordable for the proof-relevant
    # CDI subclass even though scanning every pair of all 65 ideals would add
    # little after the exact theorem.
    dimension, bound = 3, 3
    ideals = partition_downset_ideals(dimension, bound)
    bodies = [body_from_orbit_ideal(dimension, bound, ideal, i) for i, ideal in enumerate(ideals)]
    diagonal = [body for body in bodies if has_centered_diagonal_fibers(body)]
    summaries[f"diagonal-fiber-downsets-d{dimension}-M{bound}"] = summarize_family(diagonal)
    return summaries


def write_markdown(results: dict[str, object], destination: Path) -> None:
    lines = [
        "# Exact balancing-transfer scan beyond Lee balls\n",
        "All reported cross-covariogram values and increments use exact integer enumeration.\n",
    ]
    for name, summary in results.items():
        lines.extend(
            [
                f"## {name}\n",
                f"- bodies: {summary['body_count']}",
                f"- pair mode: {summary['pair_mode']}",
                f"- body pairs (including equal-body cases): {summary['pair_count']}",
                f"- transfer-edge evaluations: {summary['edge_evaluations']}",
                f"- pair signs: `{summary['pair_signs']}`",
                f"- increment range: `{summary['increment_min']}` to `{summary['increment_max']}`",
                f"- negative edges: {summary['negative_edge_count']}",
                f"- zero edges (including disjoint lenses): {summary['zero_edge_count']}",
                f"- minimal negative witness: `{summary['minimal_negative']}`",
                f"- minimal active-zero witness: `{summary['minimal_active_zero']}`\n",
            ]
        )
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    results = run_parameterized_families()
    results.update(run_downset_families())
    json_path = root / "results" / "polytope_transfer_phase_scan.json"
    markdown_path = root / "results" / "polytope_transfer_phase_scan.md"
    json_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    write_markdown(results, markdown_path)
    print(f"wrote {json_path}")
    print(f"wrote {markdown_path}")


if __name__ == "__main__":
    main()
